namespace Golf_Chip_WinRT
{
    enum NotifyType
    {
        StatusMessage,
        ErrorMessage
    };

    [default_interface]
    runtimeclass GolfChipSettings : Windows.UI.Xaml.Controls.Page
    {
        GolfChipSettings();
        
        Windows.Foundation.Collections.IObservableVector<Object> KnownDevices{ get; };
        Windows.Foundation.Collections.IObservableVector<Object> AccelerometerSettings{ get; set; };
        Windows.Foundation.Collections.IObservableVector<Object> GyroscopeSettings{ get; };
        Windows.Foundation.Collections.IObservableVector<Object> MagnetometerSettings{ get; };

        String AccelerometerName{ get; };
        String GyroscopeName{ get; };
        String MagnetometerName{ get; };

        Windows.UI.Xaml.Controls.ListView ResultsListView{ get; };

        void EnumerateButton_Click();
        void ConnectButton_Click();
        void DisconnectButton_Click();
        void UpdateSettingsButton_Click();

        Boolean Not(Boolean value);

        void NotifyUser(String strMessage, NotifyType type);
    }
}
